apiVersion: v1
kind: Secret
metadata:
  name: <PLATFORM>-<USER>.repository-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: <URL>
  # Sets user/pass authentication. Notice that the URL
  # doesn't specify a repository.
  # url: https://foo.com/my-user
  password: <PASS>
  username: <USER>
