apiVersion: v1
kind: Secret
metadata:
  name: repository-<PLATFORM>-<USER>-<REPO>
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: <REPO>
  # Sets repository url
  # url: https://foo.com/my-user/my-repo
  # url: git@github.com:sromerotech/homelab.git
