apiVersion: v1
kind: Secret
metadata:
  name: repository-credentials-<PLATFORM>-<USER>
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: <URL>
  # Sets ssh authentication
  # url: git@github.com:foo
  sshPrivateKey: |
    <CERTIFICATE_PRIVATE>
